DROP TABLE Degrees;
CREATE TABLE Degrees(
   DegreeID VARCHAR(6) NOT NULL PRIMARY KEY
  ,Degrees VARCHAR(83) NOT NULL
  ,ParentDegreeID VARCHAR(30)
);
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('DegreeID','Degrees','ParentDegreeID');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0001','Associate Degree in Administration of Justice','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0002','Associate Degree in Advertising','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0003','Associate Degree in Agribusiness','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0004','Associate Degree in Animal Management','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0005','Associate Degree in Architectural Building Engineering Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0006','Associate Degree in Architecture and Career Options','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0007','Associate Degree in Art','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0008','Associate Degree in Automotive Maintenance Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0009','Associate Degree in Aviation Mechanics','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0010','Associate Degree in Behavioral Science','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0011','Associate Degree in Boat Mechanics','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0012','Associate Degree in Boat Repair and Maintenance','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0013','Associate Degree in Cabinet Design Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0014','Associate Degree in Child Development: Program Summary','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0015','Associate Degree in Christian Ministry','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0016','Associate Degree in Cosmetology Business','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0017','Associate Degree in Digital Media','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0018','Associate Degree in Early Childhood Special Education','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0019','Associate Degree in Elementary Education','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0020','Associate Degree in English','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0021','Associate Degree in Environmental Science','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0022','Associate Degree in Environmental Studies','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0023','Associate Degree in General Psychology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0024','Associate Degree in History and Information','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0025','Associate Degree in Interdisciplinary Studies','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0026','Associate Degree in International Relations','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0027','Associate Degree in Landscape Architecture','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0028','Associate Degree in Landscaping Design','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0029','Associate Degree in Library Science','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0030','Associate Degree in Music','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0031','Associate Degree in Wildlife Management','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0032','Associate Degree in Education','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0033','Associate of Applied Science (AAS) in Accelerated Culinary Arts','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0034','Associate of Applied Science (AAS) in Accounting Specialist','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0035','Associate of Applied Science (AAS) in Administrative Support','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0036','Associate of Applied Science (AAS) in Baking and Pastry','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0037','Associate of Applied Science (AAS) in Business Administration','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0038','Associate of Applied Science (AAS) in Business Administration - Finance','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0039','Associate of Applied Science (AAS) in Business Information Systems','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0040','Associate of Applied Science (AAS) in Civil Justice - Law Enforcement','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0041','Associate of Applied Science (AAS) in Clinical Medical Assisting','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0042','Associate of Applied Science (AAS) in Computer Applications','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0043','Associate of Applied Science (AAS) in Computer Electronics','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0044','Associate of Applied Science (AAS) in Computer Game Design','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0045','Associate of Applied Science (AAS) in Computer Information Systems','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0046','Associate of Applied Science (AAS) in Culinary Arts','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0047','Associate of Applied Science (AAS) in Digital Media Communications','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0048','Associate of Applied Science (AAS) in Digital Photography','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0049','Associate of Applied Science (AAS) in Electronic Engineering','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0050','Associate of Applied Science (AAS) in Emergency Medical Services','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0051','Associate of Applied Science (AAS) in Health Care Management','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0052','Associate of Applied Science (AAS) in Health Information Management','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0053','Associate of Applied Science (AAS) in Healthcare Administration','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0054','Associate of Applied Science (AAS) in Legal Office E-ministration','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0055','Associate of Applied Science (AAS) in Telecommunications Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0056','Associate of Applied Science (AAS) in Television Production','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0057','Associate of Applied Science (AAS) in Visual Communications','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0058','Associate of Arts (AA) in Computer Information Systems','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0059','Associate of Arts (AA) in Internetworking Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0060','Associate of Arts (AA) in Psychology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0061','Associate of Arts (AA) in Interior Architecture and Design','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0062','Associate of Biotechnology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0063','Associate of Business Science (ABS) in Individualized Studies','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0064','Associate of Early Childhood Education (AECE)','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0065','Associate of Occupational Studies (AOS) in Legal Office Administration','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0066','Associate of Science (AS) in Corrections, Probation, & Parole','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0067','Associate of Science (AS) in Electronics Engineering Technology','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0068','Associate of Science (AS) in Interactive & Graphic Art','DL0001');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0069','Bachelor of�Architecture','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0070','Bachelor of Biomedical Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0071','Bachelor of Business Administration','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0072','Bachelor of�Clinical Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0073','Bachelor of Commerce','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0074','Bachelor of Computer Applications','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0075','Bachelor of Computer Information Systems','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0076','Bachelor of Science in�Construction Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0077','Bachelor of Criminal Justice','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0078','Bachelor of Divinity','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0079','Bachelor of Economics','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0080','Bachelor of Education','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0081','Bachelor of Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0082','Bachelor of Fine Arts','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0083','Bachelor of�Information Systems','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0084','Bachelor of�Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0085','Bachelor of Music','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0086','Bachelor of Pharmacy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0087','Bachelor of Philosophy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0088','Bachelor of Social Work','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0089','Bachelor of Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0090','Bachelor of Accountancy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0091','Bachelor of Arts in American Studies','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0092','Bachelor of Arts in American Indian Studies','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0093','Bachelor of Arts in Applied Psychology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0094','Bachelor of Arts in�Biology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0095','Bachelor of Arts in�Anthropology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0096','Bachelor of Arts in Child Advocacy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0097','Bachelor of Arts in Clinical Psychology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0098','Bachelor of Arts in Forensic Psychology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0099','Bachelor of Arts in Organizational Psychology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0100','Bachelor of Science�in�Aerospace Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0101','Bachelor of Science in�Actuarial','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0102','Bachelor of Science in Agriculture','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0103','Bachelor of Science in�Architecture','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0104','Bachelor of Science in�Architectural Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0105','Bachelor of Science in�Biology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0106','Bachelor of Science in�Biomedical Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0107','Bachelor of Science in�Business Administration','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0108','Bachelor of Science in�Business and Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0109','Bachelor of Science in�Chemical Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0110','Bachelor of Science in�Chemistry','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0111','Bachelor of Science in�Civil Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0112','Bachelor of Science in�Clinical Laboratory Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0113','Bachelor of Science in�Cognitive Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0114','Bachelor of Science in�Computer Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0115','Bachelor of Science in�Computer Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0116','Bachelor of Science in�Construction Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0117','Bachelor of Science in�Construction Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0118','Bachelor of Science in�Criminal Justice','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0119','Bachelor of Science in�Criminology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0120','Bachelor of Science in�Diagnostic Radiography','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0121','Bachelor of Science in�Education','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0122','Bachelor of Science in�Electrical Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0123','Bachelor of Science in�Engineering Physics','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0124','Bachelor of Science in�Engineering Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0125','Bachelor of Science in�Engineering Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0126','Bachelor of Science in�English Literature','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0127','Bachelor of Science in�Environmental Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0128','Bachelor of Science in�Environmental Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0129','Bachelor of Science in�Environmental Studies','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0130','Bachelor of Science in�Food Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0131','Bachelor of Science in�Foreign Service','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0132','Bachelor of Science in�Forensic Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0133','Bachelor of Science in�Forestry','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0134','Bachelor of Science in�History','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0135','Bachelor of Science in�Hospitality Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0136','Bachelor of Science in�Human Resources Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0137','Bachelor of Science in�Industrial Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0138','Bachelor of Science in�Information Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0139','Bachelor of Science in�Information Systems','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0140','Bachelor of Science in�Integrated Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0141','Bachelor of Science in�International Relations','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0142','Bachelor of Science in�Journalism','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0143','Bachelor of Science in�Legal Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0144','Bachelor of Science in�Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0145','Bachelor of Science in�Manufacturing Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0146','Bachelor of Science in�Marketing','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0147','Bachelor of Science in�Mathematics','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0148','Bachelor of Science in�Mechanical Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0149','Bachelor of Science in�Medical Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0150','Bachelor of Science in�Meteorology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0151','Bachelor of Science in�Microbiology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0152','Bachelor of Science in�Mining Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0153','Bachelor of Science in�Molecular Biology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0154','Bachelor of Science in�Neuroscience','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0155','Bachelor of Science in�Nursing','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0156','Bachelor of Science in�Nutrition science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0157','Bachelor of Science in�Software Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0158','Bachelor of Science in�Petroleum Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0159','Bachelor of Science in�Podiatry','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0160','Bachelor of Science in�Pharmacology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0161','Bachelor of Science in�Pharmacy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0162','Bachelor of Science in�Physical Therapy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0163','Bachelor of Science in�Physics','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0164','Bachelor of Science in�Plant Science','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0165','Bachelor of Science in�Politics','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0166','Bachelor of Science in�Psychology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0167','Bachelor of Science in�Public Safety','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0168','Bachelor of Science in�Quantity Surveying Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0169','Bachelor of Science in�Radiologic Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0170','Bachelor of Science in�Real-Time Interactive Simulation','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0171','Bachelor of Science in�Religion','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0172','Bachelor of Science in�Respiratory Therapy','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0173','Bachelor of Science in�Risk Management�and�Insurance','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0174','Bachelor of Science in�Science Education','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0175','Bachelor of Science in�Sports Management','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0176','Bachelor of Science in�Systems Engineering','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0177','Bachelor of Music in�Jazz Studies','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0178','Bachelor of Music in�Composition','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0179','Bachelor of Music in�Performance','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0180','Bachelor of Music in�Theory','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0181','Bachelor of Music in�Music Education','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0182','Bachelor of Science in�Veterinary Technology','DL0002');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0183','Master of Accountancy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0184','Master of Advanced Study','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0185','Master of Applied Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0186','Master of Applied Mathematical Sciences','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0187','Master of Applied Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0188','Master of Architecture','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0189','Master of Arts','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0190','Master of Arts in Liberal Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0191','Master of Arts in Strategic Communication Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0192','Master of Arts in Teaching','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0193','Master of Bioinformatics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0194','Master of Business Administration','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0195','Master of Business Management of Technology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0196','Master of Business','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0197','Master of Business Economics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0198','Master of Business Engineering','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0199','Master of Business Informatics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0200','Master of Chemistry','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0201','Master of City Planning','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0202','Master of Commerce','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0203','Master of Computational Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0204','Master of Computer Applications','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0205','Master of Computer Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0206','Master of Communication','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0207','Master of Counseling','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0208','Master of Criminal Justice','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0209','Master in Creative Technologies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0210','Master of Design','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0211','Master of Divinity','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0212','Master of Economics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0213','Master of Education','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0214','Master of Educational Technology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0215','Master of Engineering','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0216','Master of Engineering Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0217','Master of Enterprise','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0218','Master of European Law','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0219','Master of Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0220','Master of Financial Economics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0221','Master of Financial Engineering','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0222','Master of Financial Mathematics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0223','Master of Fine Arts','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0224','Master of Health Administration','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0225','Master of Health Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0226','Master of Humanities','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0227','Master of Industrial and Labor Relations','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0228','Master of International Affairs','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0229','Master of International Business','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0230','Master of International Economics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0231','Master of International Public Policy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0232','Master of International Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0233','Master of Information','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0234','Master of Information Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0235','Master of Information System Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0236','Master of Islamic Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0237','Master of IT','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0238','Master of Jurisprudence','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0239','Master of Laws','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0240','Master of Studies in Law','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0241','Master of Landscape Architecture','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0242','Master of Letters','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0243','Master of Liberal Arts','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0244','Master of Library and Information Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0245','Master of Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0246','Master of Mass Communication and Journalism','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0247','Master of Mathematical Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0248','Master of Mathematics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0249','Master of Mathematics and Computer Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0250','Master of Mathematics and Philosophy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0251','Master of Medical Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0252','Master of Medicine','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0253','Master of Military Art and Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0254','Master of Music','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0255','Master of Network and Communications Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0256','Master of Occupational Therapy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0257','Master of Pharmacy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0258','Master of Philosophy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0259','Master of Physician Assistant Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0260','Master of Physics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0261','Master of Political Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0262','Master of Professional Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0263','Master of Psychology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0264','Master of Public Administration','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0265','Master of Public Affairs','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0266','Master of Public Diplomacy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0267','Master of Public Health','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0268','Master of Public Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0269','Master of Public Policy','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0270','Master of Public Relations','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0271','Master of Public Service','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0272','Master of Quantitative Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0273','Master of Rabbinic Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0274','Master of Real Estate Development','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0275','Master of Religious Education','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0276','Master of Research','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0277','Master of Sacred Music','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0278','Master of Sacred Theology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0279','Master of Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0280','Master of Science in Applied Cognition and Neuroscience','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0281','Master of Science in Bioinformatics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0282','Master of Science in Clinical Epidemiology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0283','Master of Science in Computing Research','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0284','Master of Science in Cyber Security','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0285','Master of Science in Education','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0286','Master of Science in Engineering','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0287','Master of Science in Development Administration','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0288','Master of Science in Finance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0289','Master of Science in Governance & Organizational Sciences','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0290','Master of Science in Government Contracts','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0291','Master of Science in Health Informatics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0292','Master of Science in Human Resource Development','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0293','Master of Science in Information Assurance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0294','Master of Science in Information Systems','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0295','Master of Science in Information Technology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0296','Master of Science in Leadership','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0297','Master of Science in Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0298','Master of Science in Nursing','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0299','Master of Science in Project Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0300','Master of Science in Quality Assurance','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0301','Master of Science in Risk Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0302','Master of Science in Supply Chain Management','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0303','Master of Science in Teaching','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0304','Master of Science in Taxation','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0305','Master of Social Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0306','Master of Social Work','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0307','Master of Statistics','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0308','Master of Strategic Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0309','Master of Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0310','Master of Surgery','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0311','Master of Theological Studies','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0312','Master of Technology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0313','Master of Theology','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0314','Master of Urban Planning','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0315','Master of Veterinary Science','DL0003');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0316','Doctor of Business Administration','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0317','Doctor of Canon Law','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0318','Doctor of Chiropractic','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0319','Doctor of Commerce','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0320','Doctor of Dental Surgery','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0321','Doctor of Divinity','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0322','Doctor of Education','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0323','Doctor of Engineering','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0324','Doctor of Health Administration','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0325','Doctor of Health Science','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0326','Doctor of Juridical Science;�Juris Doctor','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0327','Doctor of Law;�Legum Doctor','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0328','Doctor of Liberal Studies','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0329','Doctor of Management','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0330','Doctor of Medicine','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0331','Doctor of Ministry','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0332','Doctor of Musical Arts','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0333','Doctor of Naturopathic Medicine','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0334','Doctor of Optometry','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0335','Doctor of Osteopathic Medicine','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0336','Doctor of Pharmacy','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0337','Doctor of Philosophy','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0338','Doctor of Public Administration','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0339','Doctor of Science','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0340','Doctor of Theology','DL0004');
INSERT INTO Degrees(DegreeID,Degrees,ParentDegreeID) VALUES ('D0341','Doctor of Veterinary Medicine','DL0004');
